### ISSUE TITLE
Error raised on `ps` when no containers are running

### ISSUE THREAD

**Issue by bjjb** [xeger/docker#1]
If you have no containers running on your `DOCKER_HOST`, you can still run `docker ps`, and the output simply indicates that nothing is running. `Docker::Session#ps`, however, raises the following error:

```
Docker::Error: 'inspect' failed with status 256: docker: "inspect" requires a minimum of 1 argument.
```

The `#inspect` method should be able to handle an empty array, and `#ps` should return this.

**Comment by xeger** [comment]
Merged; thank you for the contribution, and sorry for the exceedingly long delay ... GitHub evidently decided not to notify me when you opened the new issue, or I missed the notification.
