### ISSUE TITLE
Capturing container STDOUT in real time as an IO stream

### ISSUE THREAD

**Issue by vovimayhem** [xeger/docker#5]
Is there any way to capture the STDOUT in real time? I've been looking at [the Backticks README section about real time capture](https://github.com/xeger/backticks#interactivity-and-real-time-capture), but nothing I do can capture each output from a given running container.

I'm testing with the codeclimate CLI, which supposedly streams each found issue to the stdout.

**Comment by vovimayhem** [comment]
I was comparing to the wrong version of [backticks gem](https://github.com/xeger/backticks)(Version 0.5.0)... Is there anything blocking this gem from using version 1.0.0?

**Comment by vovimayhem** [comment]
...I tried it myself and found no problems at all...

I'll send another PR with how I did it, basically allowing `Docker::Session#run` and `Docker::Session#run!` to allow receiving a block, and tapping into `cmd` with the given block.

**Comment by vovimayhem** [comment]
Sorry for the delay @xeger but here it is!

**Comment by xeger** [comment]
Thanks for the contribution! Added some YARD to explain how to use capture, merged, and published v0.4.0.

P.S. since you've contributed excellent work twice now, you are a maintainer. Welcome to the club!

**Comment by vovimayhem** [comment]
Excellent! You'll still be controlling the gem publishing, or you plan to add me as a contributor also at rubygems.org?

We're doing a lot of docker running & other stuff from ruby in several projects here at [IcaliaLabs](https://github.com/IcaliaLabs). I wouldn't be surprised to see more PR's and activity from our part over this project.

**Comment by xeger** [comment]
It probably makes sense to give you gem ownership. I'll need your email to do that; you can send it to me privately - xeger at xeger dot net
